練習list作業
amusements/great_shows pull request #23
Opened 2018-07-07 01:47 UTC by Linda0924

2018-07-07 04:29 UTC, rikalin commented on linda_practice/linda_re_rule.py
> +#plants = ["Orchild", "Orange", "Leon Tree", "Red Pepper"]
建議把沒有用處的程式碼刪除，例如未使用的參數、註解的程式碼。

2018-07-07 04:30 UTC, rikalin commented on linda_practice/linda_re_rule.py
> +    print ("No car to wash")
建議把沒有用處的程式碼刪除，例如未使用的參數、註解的程式碼。

2018-07-07 04:43 UTC, rikalin requested changes
linda.py 請修改產出的 list，避免造成 output 錯誤 
linda_re_rule.py 程式碼建議把沒有用到的程式碼刪除

2018-07-07 04:43 UTC, rikalin commented on py_0501_list_stack/linda.py
> +
Q1 list 陣列不正確題目為 1~20數值平方不該包含數值 0，並且 output 多了 0
因為 Q1 產出的陣列錯誤造成 Q2 取得錯誤的值

2018-07-08 10:23 UTC, Linda0924 commented on py_0501_list_stack/linda.py
> +
修正請見下方“fix: Q1 list 錯誤修正”，謝謝。

2018-07-08 12:54 UTC, rikalin reviewed
請調整 linda_re_rule.py 檔案路徑，並修正 linda.py。

2018-07-08 12:54 UTC, rikalin commented on py_0501_list_stack/linda.py
>  print (squares[0:6])
Q1 題目 “print the first 5 elements” 此行印出了 6 個，請修正。

2018-07-08 12:54 UTC, rikalin commented on linda_practice/linda_re_rule.py
>  animals = ["Mickey Mouse", "Cat", "Cow"]
animals 這個參數並未使用，建議刪除。另外此檔案存放位置錯誤，檔案路徑應該為 great_shows/py_03_for_else/linda_re_rule.py

2018-07-08 13:25 UTC, rikalin approved these changes

2018-10-15 13:21 UTC, merged